apiVersion: v1
kind: Service
metadata:
  name: expenses-service
  labels:
    app: expenses-service
spec:
  selector:
    app: expenses-service
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
